2021-09-25 20:22:38,925 ERROR: Exception on /user/zhushiwei [GET] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\main\routes.py", line 72, in user
    return render_template('user.html', user=user, posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\user.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\base.html", line 75, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\user.html", line 37, in block 'app_content'
    {% include '_post.html' %}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\_post.html", line 9, in top-level template code
    <!--            <a href="{{ url_for('user', username=post.author.username) }}">-->
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2021-09-25 20:24:03,124 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 20:24:09,890 ERROR: Exception on /explore [GET] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\main\routes.py", line 60, in explore
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 3, in block 'doc'
    {%- block html %}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 19, in block 'html'
    {% block body -%}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 22, in block 'body'
    {% block content -%}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\base.html", line 75, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\index.html", line 12, in block 'app_content'
    {% include '_post.html' %}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\_post.html", line 9, in top-level template code
    <!--            <a href="{{ url_for('user', username=post.author.username) }}">-->
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2021-09-25 20:29:34,108 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 20:29:35,382 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 20:30:58,817 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 20:31:00,103 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 20:33:25,273 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 20:33:26,535 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
