2021-09-25 19:44:54,720 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 19:45:09,395 ERROR: Exception on /auth/login [GET] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 27, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2021-09-25 19:49:09,335 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 19:49:10,826 ERROR: Exception on /auth/login [GET] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 27, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2021-09-25 19:50:55,870 ERROR: Exception on /auth/login [GET] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 27, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2021-09-25 19:51:02,172 ERROR: Exception on /auth/login [GET] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 27, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2021-09-25 19:52:24,170 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
