2021-09-25 19:52:26,921 ERROR: Exception on /auth/login [GET] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 27, in login
    return render_template('login.html', title='Sign In', form=form)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: login.html
2021-09-25 19:54:39,540 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 19:55:30,547 ERROR: Exception on /explore [GET] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_login\utils.py", line 272, in decorated_view
    return func(*args, **kwargs)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\main\routes.py", line 60, in explore
    return render_template('index.html', title='Explore', posts=posts.items, next_url=next_url, prev_url=prev_url)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\index.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\base.html", line 75, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\index.html", line 12, in block 'app_content'
    {% include '_post.html' %}
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\templates\_post.html", line 9, in top-level template code
    <!--            <a href="{{ url_for('user', username=post.author.username) }}">-->
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'user' with values ['username']. Did you mean 'main.user' instead?
2021-09-25 19:57:29,493 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 19:57:43,891 ERROR: Exception on /auth/reset_password_request [GET] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 62, in reset_password_request
    return render_template('reset_password_request.html', title='Reset Password', form=form)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 148, in render_template
    ctx.app.jinja_env.get_or_select_template(template_name_or_list),
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 1068, in get_or_select_template
    return self.get_template(template_name_or_list, parent, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 997, in get_template
    return self._load_template(name, globals)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\environment.py", line 958, in _load_template
    template = self.loader.load(self, name, self.make_globals(globals))
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\jinja2\loaders.py", line 125, in load
    source, filename, uptodate = self.get_source(environment, name)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 59, in get_source
    return self._get_source_fast(environment, template)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\templating.py", line 95, in _get_source_fast
    raise TemplateNotFound(template)
jinja2.exceptions.TemplateNotFound: reset_password_request.html
2021-09-25 19:58:37,329 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
