2021-09-25 19:58:42,278 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 59, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\models.py", line 49, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-09-25 20:00:25,647 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 20:00:35,623 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 59, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\models.py", line 49, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-09-25 20:02:28,066 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 20:02:30,348 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 59, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\models.py", line 49, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-09-25 20:03:16,987 INFO: Microblog startup [in C:\Users\¼ÅÄ¯ºî\microblog\app\__init__.py:57]
2021-09-25 20:03:20,003 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 59, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\models.py", line 49, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-09-25 20:03:22,629 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 59, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\models.py", line 49, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
2021-09-25 20:04:22,980 ERROR: Exception on /auth/reset_password_request [POST] [in C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\¼ÅÄ¯ºî\AppData\Local\Programs\Python\Python38\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\routes.py", line 59, in reset_password_request
    send_password_reset_email(user)
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\auth\email.py", line 20, in send_password_reset_email
    token = user.get_reset_password_token()
  File "C:\Users\¼ÅÄ¯ºî\microblog\app\models.py", line 49, in get_reset_password_token
    return jwt.encode(
AttributeError: 'str' object has no attribute 'decode'
